version: '3'
services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URI=http://localhost:4000
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "4000:4000"  # Ports pour le backend
